[theme]
primaryColor = "#0000ff"  # Cor verde para o textbox
backgroundColor = "#FFFFFF"  # Cor branca para o secondaryBackgroundColor
secondaryBackgroundColor = "#469536"  # Cor verde clara
textColor = "#000000"  # Cor preta para o texto (título)
font = "sans serif"